Pull Request #1
nvclon/SpeedTyping pull request #1
Opened 2023-04-16 15:29 UTC by nvclon

Typing exactly the same as the text above the line as fast as you can 
Scoring system
To exit press ESCAPE
Starts with main.py file

2023-04-25 22:09 UTC, Andy-Messer commented
![image](https://user-images.githubusercontent.com/90355814/234415185-8849c3d6-55c7-4b42-b864-8a6f0a5d5b93.png)
база + 2 допа есть

2023-04-25 22:11 UTC, Andy-Messer requested changes
По коду ок, раскидай по директориям музыку в music. Тексты в data. Код в src. и тд

2023-05-12 12:27 UTC, nvclon commented
Changed code structure, project comment

2023-05-12 13:18 UTC, nvclon commented
Completely new README.md

2023-05-15 22:42 UTC, merged